openapi: 3.1.0
info:
  title: Authentication API Documentation
  description: Authentication API documentation for developers
  version: 1.0.0
  contact:
    name: 'Authentication API Development from Scratch'
    url: 'hasibiqbal.dev'

servers:
- url: http://localhost:4010/api/v1
  description: Development Server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    AdminAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    UserAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths: {}
