openapi: 3.0.0
tags:
- name: Two-Factor Authentication
  description: API endpoints for managing two-factor authentication

paths:
  /auth/2fa/setup:
    get:
      tags:
      - Two-Factor Authentication
      summary: Setup two-factor authentication
      description: Initiates the 2FA setup process by generating a secret and QR code
      security:
      - bearerAuth: []
      responses:
        '200':
          description: 2FA setup initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "2FA setup initiated successfully"
                  data:
                    type: object
                    properties:
                      qrCodeUrl:
                        type: string
                        description: QR code URL to be scanned by authentication app
                        example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA..."
                      secret:
                        type: string
                        description: Secret key to be manually entered in authentication app
                        example: "ABCDEFGHIJKLMNOP"
        '400':
          description: Failed to setup 2FA
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "2FA setup failed"
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "2FA_SETUP_FAILED"

  /auth/2fa/enable:
    post:
      tags:
      - Two-Factor Authentication
      summary: Enable two-factor authentication
      description: Enables 2FA by verifying the token from the authentication app
      security:
      - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - token
              properties:
                token:
                  type: string
                  description: Token from authentication app
                  example: "123456"
      responses:
        '200':
          description: 2FA enabled successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "2FA enabled successfully"
                  data:
                    type: object
                    properties:
                      backupCodes:
                        type: array
                        description: Backup codes for 2FA recovery
                        items:
                          type: string
                        example: [ "A1B2C3D4", "E5F6G7H8", "I9J0K1L2" ]
        '400':
          description: Failed to enable 2FA
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Failed to enable 2FA"
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "2FA_ENABLE_FAILED"

  /auth/2fa/disable:
    post:
      tags:
      - Two-Factor Authentication
      summary: Disable two-factor authentication
      description: Disables 2FA for the authenticated user
      security:
      - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - password
              properties:
                password:
                  type: string
                  description: User's password for security verification
                  example: "securePassword123"
      responses:
        '200':
          description: 2FA disabled successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "2FA disabled successfully"
        '400':
          description: Failed to disable 2FA
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Failed to disable 2FA"
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "2FA_DISABLE_FAILED"

  /auth/2fa/verify:
    post:
      tags:
      - Two-Factor Authentication
      summary: Verify two-factor authentication
      description: Verifies a 2FA token or backup code
      security:
      - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - token
              properties:
                token:
                  type: string
                  description: Token from authentication app or backup code
                  example: "123456"
      responses:
        '200':
          description: 2FA verification successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "2FA verification successful"
        '401':
          description: 2FA verification failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Invalid 2FA code"
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "2FA_VERIFICATION_FAILED"

  /auth/2fa/generate-backup-codes:
    post:
      tags:
      - Two-Factor Authentication
      summary: Generate new backup codes
      description: Generates a new set of backup codes for 2FA recovery
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Backup codes generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Backup codes generated successfully"
                  data:
                    type: object
                    properties:
                      backupCodes:
                        type: array
                        description: New backup codes for 2FA recovery
                        items:
                          type: string
                        example: [ "M3N4O5P6", "Q7R8S9T0", "U1V2W3X4" ]
        '400':
          description: Failed to generate backup codes
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Failed to generate backup codes"
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "BACKUP_CODES_GENERATION_FAILED"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
