openapi: 3.0.0
info:
  title: Password Management APIs
  description: API endpoints for password management functionality including forgot password, reset password, and change password.
  version: 1.0.0

tags:
- name: Password Management
  description: Endpoints for managing user passwords

paths:
  /auth/password/forgot-password:
    post:
      tags:
      - Password Management
      summary: Request password reset
      description: Sends a password reset link to the user's email if the account exists
      operationId: forgotPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: user@example.com
      responses:
        '200':
          description: Password reset instructions sent if email exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: If your email is registered, you will receive password reset instructions
        '400':
          description: Invalid email provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Please provide a valid email address
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: INVALID_EMAIL
        '429':
          description: Too many reset attempts
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Too many reset attempts. Try again later.
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: TOO_MANY_REQUESTS
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Failed to process password reset request
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: PASSWORD_RESET_REQUEST_FAILED

  /auth/password/reset-password:
    post:
      tags:
      - Password Management
      summary: Reset password using token
      description: Resets a user's password using the token received in email
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - token
              - newPassword
              properties:
                token:
                  type: string
                  description: Password reset token received via email
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                newPassword:
                  type: string
                  format: password
                  description: New password that meets security requirements
                  example: StrongP@ssw0rd
      responses:
        '200':
          description: Password reset successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Password reset successful
        '400':
          description: Invalid reset token or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid or expired reset token
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: INVALID_RESET_TOKEN
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Failed to reset password
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: PASSWORD_RESET_FAILED

  /auth/password/change-password:
    put:
      tags:
      - Password Management
      summary: Change password for authenticated user
      description: Allows an authenticated user to change their password
      operationId: changePassword
      security:
      - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - currentPassword
              - newPassword
              - confirmPassword
              properties:
                currentPassword:
                  type: string
                  format: password
                  description: User's current password
                  example: CurrentP@ss123
                newPassword:
                  type: string
                  format: password
                  description: New password that meets security requirements
                  example: NewStrongP@ss456
                confirmPassword:
                  type: string
                  format: password
                  description: Confirmation of new password
                  example: NewStrongP@ss456
      responses:
        '200':
          description: Password changed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Password changed successfully
        '400':
          description: Invalid password or passwords don't match
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: New passwords do not match
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: PASSWORD_MISMATCH
        '401':
          description: Incorrect current password or unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Current password is incorrect
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: INVALID_PASSWORD
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Failed to change password
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: PASSWORD_CHANGE_FAILED

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained after login
